name: MovieNight
options:
  bundleIdPrefix: com.movienight
  deploymentTarget:
    tvOS: "17.0"
settings:
  WEBVIEW_URL: http://localhost:3000
targets:
  MovieNight:
    type: application
    platform: tvOS
    sources:
      - Sources
    settings:
      INFOPLIST_FILE: Sources/Info.plist
      DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
      PRODUCT_BUNDLE_IDENTIFIER: com.movienight.app
      SWIFT_OBJC_BRIDGING_HEADER: Sources/BridgingHeader.h
      CODE_SIGN_STYLE: Automatic
      ASSETCATALOG_COMPILER_APPICON_NAME: "App Icon & Top Shelf Image"
